In [4]:
#LAB 11
#1-1
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

#1-2
b=np.array([i for i in range(10)])
print(b)

#1-3
c=np.array(range(0,10,2))
print(c)

#1-4
print('c.shape =',c.shape)
print('c.ndim =',c.ndim)
print('c.dtype =',c.dtype)
print('c.size =',c.size)
print('c.itemsize =',c.itemsize)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
c.shape = (5,)
c.ndim = 1
c.dtype = int32
c.size = 5
c.itemsize = 4


In [7]:
#2-1
a=np.array([23,45,67,7,2,30,34,82])
print(a)
print('최댓값 :',a.max())
print('최솟값 :',a.min())
print('평균값 :',a.mean())

#2-2
b=np.random.randint(0,99,size=10)
print('b =',b)
print('최댓값 :',b.max())
print('최솟값 :',b.min())
print('평균값 :',b.mean())

#2-3
c=np.append(a,b)
print('c =',c)

[23 45 67  7  2 30 34 82]
최댓값 : 82
최솟값 : 2
평균값 : 36.25
b = [31 49 86 68 98 90 55 26  0 70]
최댓값 : 98
최솟값 : 0
평균값 : 57.3
c = [23 45 67  7  2 30 34 82 31 49 86 68 98 90 55 26  0 70]


In [11]:
#3-1
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[2,2,2],[2,2,2],[2,2,2]])
print(a)
print(b)
print('=================================')
#3-2
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a@b)
print(a**2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[12 12 12]
 [30 30 30]
 [48 48 48]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [16]:
#4-1
import numpy as np
a1=np.full((3,3),2)
print(a1)

#4-2
a2=np.arange(1,12+1)
print(a2)

#4-3
a3=np.arange(3,50+1,3)
print(a3)

#4-4
a4=np.linspace(0,20,5)
print(a4)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[ 0.  5. 10. 15. 20.]


In [6]:
#5-1
import numpy as np
a1=np.arange(1,13)
a1=np.arange(1,13).reshape(2,6)
print(a1)
print()
#6-2
a2=np.arange(1,31)
a2=np.arange(1,31).reshape(3,10)
print(a2)
print()
#5-3
a3=np.arange(1,31).reshape(6,5)
print(a3)
print()
#5-4
a4=np.transpose(a3)
print(a4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [17]:
#6-1
a=np.random.randint(1,101,size=15)
a=a.reshape(3,5)############name=name.reshape(m,n) mxn
print(a)
#6-2
print('a의 열방향 최댓값 :',a.max(axis=0))
print('a의 열방향 최솟값 :',a.min(axis=0))
print('a의 열방향 평균 :',a.mean(axis=0))
#6-3
print('a의 행방향 최댓값 :',a.max(axis=1))
print('a의 행방향 최솟값 :',a.min(axis=1))
print('a의 행방향 평균 ',a.mean(axis=1))

[[65  2 28 64 82]
 [36 87 62 89 19]
 [84 16 47 99 41]]
a의 열방향 최댓값 : [84 87 62 99 82]
a의 열방향 최솟값 : [36  2 28 64 19]
a의 열방향 평균 : [61.66666667 35.         45.66666667 84.         47.33333333]
a의 행방향 최댓값 : [82 89 99]
a의 행방향 최솟값 : [ 2 19 16]
a의 행방향 평균  [48.2 58.6 57.4]


In [25]:
#7-1
a=np.arange(1,11)
print(a)
b=(a[1:8:2])
print(b)

#7-2
b=a[5:]
print(b)
c=a[6:]
print(c)
d=a[:3]
print(d)
e=a[0::2]
print(e)
f=a[-1::-2]
print(f)

[ 1  2  3  4  5  6  7  8  9 10]
[2 4 6 8]
[ 6  7  8  9 10]
[ 7  8  9 10]
[1 2 3]
[1 3 5 7 9]
[10  8  6  4  2]


In [30]:
#8-1
a=np.arange(0,24).reshape(4,3,2)
print('index       elememt')
for x in range(0,4):
    for y in range(0,3):
        for z in range(0,2):
            print('({},{},{})      {}'.format(x,y,z,a[x][y][z]))
            
#8-2
print(np.concatenate((a[0][0],a[1][0]),axis=0))
print(np.concatenate((a[0][0],a[2][1]),axis=0))
print(np.concatenate((a[0],a[1]),axis=0))
print(np.concatenate((a[0],a[1]),axis=1))#####################################3

index       elememt
(0,0,0)      0
(0,0,1)      1
(0,1,0)      2
(0,1,1)      3
(0,2,0)      4
(0,2,1)      5
(1,0,0)      6
(1,0,1)      7
(1,1,0)      8
(1,1,1)      9
(1,2,0)      10
(1,2,1)      11
(2,0,0)      12
(2,0,1)      13
(2,1,0)      14
(2,1,1)      15
(2,2,0)      16
(2,2,1)      17
(3,0,0)      18
(3,0,1)      19
(3,1,0)      20
(3,1,1)      21
(3,2,0)      22
(3,2,1)      23
[0 1 6 7]
[ 0  1 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [9]:
#9-1
import numpy as np
a=np.arange(16).reshape(4,4)
b=a[:,1]
print('b =',b)
c=a[2,1:]
print('c= ',c)
d=a[:2,:2]
print('d =',d)
e=a[1:3,1:3]
print('e =',e)

#9-2
f=a[:2,:3].flatten()
print('f = ',f)
g=a[2:,].flatten()
print('g = ',g)
h=a[1::2,1:].flatten()
print('h = ',h)

b = [ 1  5  9 13]
c=  [ 9 10 11]
d = [[0 1]
 [4 5]]
e = [[ 5  6]
 [ 9 10]]
f =  [0 1 2 4 5 6]
g =  [ 8  9 10 11 12 13 14 15]
h =  [ 5  6  7 13 14 15]


In [28]:
#10-1
a=np.array([[1,1,-1],[2,-1,3],[1,2,1]])
b=np.array([0,9,8])
(ans)=np.linalg.solve(a,b)
print('x={:.1f} y={} z={:.1f}'.format(ans[0],ans[1],ans[2]))
#10-2
A=np.array([[1,1,-1],[2,-1,3],[1,2,1]],dtype='int32')
print('det(A) = {:.1f}'.format(np.linalg.det(A)))
#10-3
a1 = np.array([[-1, 3], [2, 1]])
a2 = np.array([[2, 3], [1, 1]])
a3 = np.array([[2, -1], [1, 2]])
det = 1 * np.linalg.det(a1) - 1 * np.linalg.det(a2) - 1 * np.linalg.det(a3)
print('det(A) = {:4.1f}'.format(det))

x=1.0 y=2.0 z=3.0
det(A) = -11.0
det(A) = -11.0
